// Package ffmpeg builds FFmpeg concat-demuxer files and drives the FFmpeg binary
// to encode a timelapse. It implements domain.ConcatBuilder and domain.Encoder,
// keeping all FFmpeg-specific knowledge (argument layout, filter graph, concat
// syntax) isolated from the core use case.
package ffmpeg

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/victoraldir/focal/pkg/domain"
)

// ConcatGenerator implements domain.ConcatBuilder. It writes a temporary text
// file in FFmpeg's concat-demuxer format describing the ordered frames and how
// long each should be shown.
type ConcatGenerator struct {
	// tempDir overrides the directory used for the temp file; empty means the OS
	// default. Exposed for tests so generated files are easy to locate and assert on.
	tempDir string
}

// NewConcatGenerator returns a ConcatGenerator writing to the OS temp directory.
func NewConcatGenerator() *ConcatGenerator { return &ConcatGenerator{} }

// Build writes the concat file for the given ordered images at the target fps
// and returns its path plus a cleanup function that removes it. Each frame is
// held for 1/fps seconds. Per the concat-demuxer contract the final file entry
// is repeated without a trailing duration so FFmpeg renders the last frame for
// the intended time rather than dropping it.
func (g *ConcatGenerator) Build(images []domain.Image, fps int) (string, func() error, error) {
	if len(images) == 0 {
		return "", nil, fmt.Errorf("cannot build concat file from an empty sequence")
	}
	if fps <= 0 {
		return "", nil, fmt.Errorf("fps must be positive, got %d", fps)
	}

	f, err := os.CreateTemp(g.tempDir, "focal-concat-*.txt")
	if err != nil {
		return "", nil, fmt.Errorf("creating temp concat file: %w", err)
	}
	path := f.Name()
	cleanup := func() error { return os.Remove(path) }

	if _, err := f.WriteString(renderConcat(images, fps)); err != nil {
		f.Close()
		_ = cleanup()
		return "", nil, fmt.Errorf("writing concat file: %w", err)
	}
	if err := f.Close(); err != nil {
		_ = cleanup()
		return "", nil, fmt.Errorf("closing concat file: %w", err)
	}
	return path, cleanup, nil
}

// renderConcat produces the concat-demuxer document. It is separated from disk
// I/O so its exact output can be asserted directly in unit tests.
func renderConcat(images []domain.Image, fps int) string {
	duration := 1.0 / float64(fps)

	var b strings.Builder
	b.WriteString("# Generated by focal - FFmpeg concat demuxer file\n")
	for _, img := range images {
		fmt.Fprintf(&b, "file '%s'\n", escapeConcatPath(img.Path))
		fmt.Fprintf(&b, "duration %.6f\n", duration)
	}
	// Repeat the last frame so its duration is honoured by the demuxer.
	fmt.Fprintf(&b, "file '%s'\n", escapeConcatPath(images[len(images)-1].Path))
	return b.String()
}

// escapeConcatPath prepares a path for inclusion inside single quotes in a
// concat file.
//
// Two transforms are applied. First, backslash separators are converted to
// forward slashes via filepath.ToSlash — a no-op on Unix, but essential on
// Windows: the concat demuxer treats "\" as an escape character, so a raw
// "C:\Users\...\img.jpg" would be mis-parsed. FFmpeg accepts "C:/Users/..." on
// Windows, so forward slashes are both safe and unambiguous. Second, single
// quotes are escaped per FFmpeg's rule — close the quote, emit an escaped quote,
// reopen: ' -> '\”.
func escapeConcatPath(path string) string {
	return strings.ReplaceAll(filepath.ToSlash(path), "'", `'\''`)
}
